---

- name: Install Mariadb on Ubuntu
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pip
      - python3-mysqldb
    state: latest

- name: Configure mysql server
  template:
    src: server-512M.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/60-my-server.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: Remove MariaDB anonymous user
  mysql_user: name='' host_all=yes state=absent

- name: Drop MariaDB test db
  mysql_db: name=test state=absent
